# Generated by Django 4.2.7 on 2026-01-22 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('total_points', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Points totaux')),
                ('time_limit', models.IntegerField(blank=True, null=True, verbose_name='Limite de temps (minutes)')),
                ('passing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note de passage')),
                ('allow_multiple_attempts', models.BooleanField(default=False, verbose_name='Autoriser plusieurs tentatives')),
                ('max_attempts', models.IntegerField(default=1, verbose_name='Nombre maximum de tentatives')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='Mélanger les questions')),
                ('show_results_immediately', models.BooleanField(default=True, verbose_name='Afficher les résultats immédiatement')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='schools.schoolclass', verbose_name='Classe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='schools.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Choix multiples'), ('TRUE_FALSE', 'Vrai/Faux'), ('SHORT_ANSWER', 'Réponse courte'), ('ESSAY', 'Dissertation')], max_length=20, verbose_name='Type de question')),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Points')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('option_a', models.CharField(blank=True, max_length=500, null=True, verbose_name='Option A')),
                ('option_b', models.CharField(blank=True, max_length=500, null=True, verbose_name='Option B')),
                ('option_c', models.CharField(blank=True, max_length=500, null=True, verbose_name='Option C')),
                ('option_d', models.CharField(blank=True, max_length=500, null=True, verbose_name='Option D')),
                ('correct_answer', models.CharField(max_length=10, verbose_name='Bonne réponse')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='elearning.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question de quiz',
                'verbose_name_plural': 'Questions de quiz',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Commencé le')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Réussi')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='elearning.quiz', verbose_name='Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='accounts.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL vidéo')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='courses/attachments/', verbose_name='Pièces jointes')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Date limite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.schoolclass', verbose_name='Classe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Fichier du devoir')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'attribution")),
                ('due_date', models.DateTimeField(verbose_name='Date limite')),
                ('total_points', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Points totaux')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='elearning.course', verbose_name='Cours')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schools.schoolclass', verbose_name='Classe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schools.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Devoir',
                'verbose_name_plural': 'Devoirs',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Réponse')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Points obtenus')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='elearning.quizattempt', verbose_name='Tentative')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='elearning.quizquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse de quiz',
                'verbose_name_plural': 'Réponses de quiz',
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Fichier de soumission')),
                ('submission_text', models.TextField(blank=True, null=True, verbose_name='Texte de soumission')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Soumis le')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Noté le')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Soumis'), ('GRADED', 'Noté'), ('LATE', 'En retard')], default='SUBMITTED', max_length=20, verbose_name='Statut')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='elearning.assignment', verbose_name='Devoir')),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='accounts.teacher', verbose_name='Noté par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Soumission de devoir',
                'verbose_name_plural': 'Soumissions de devoirs',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
