# Generated by Django 4.2.7 on 2026-01-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Choix unique'), ('MULTIPLE_CHOICE', 'Choix multiple'), ('TEXT', 'Texte'), ('NUMBER', 'Nombre')], max_length=20, verbose_name='Type')),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Points')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('option_a', models.CharField(blank=True, max_length=500, null=True, verbose_name='Option A')),
                ('option_b', models.CharField(blank=True, max_length=500, null=True, verbose_name='Option B')),
                ('option_c', models.CharField(blank=True, max_length=500, null=True, verbose_name='Option C')),
                ('option_d', models.CharField(blank=True, max_length=500, null=True, verbose_name='Option D')),
                ('correct_answer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Réponse correcte')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='elearning.assignment', verbose_name='Devoir')),
            ],
            options={
                'verbose_name': 'Question de devoir',
                'verbose_name_plural': 'Questions de devoir',
                'ordering': ['order'],
            },
        ),
    ]
