# Generated by Django 4.2.7 on 2026-01-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_add_assignment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'Choix unique'), ('MULTIPLE_CHOICE', 'Choix multiple'), ('TEXT', 'Texte'), ('NUMBER', 'Nombre'), ('TRUE_FALSE', 'Vrai/Faux'), ('SHORT_ANSWER', 'Réponse courte'), ('ESSAY', 'Dissertation')], max_length=20, verbose_name='Type de question'),
        ),
    ]
