# Generated by Django 4.2.7 on 2026-02-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_quiz_question_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Bonne réponse'),
        ),
    ]
