# Generated by Django 4.2.7 on 2026-02-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_quiz_question_correct_answer_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='teacher_feedback',
            field=models.TextField(blank=True, null=True, verbose_name="Commentaire de l'enseignant"),
        ),
    ]
