# Generated by Django 4.2.7 on 2026-01-26 13:09

from django.db import migrations, models
import django.db.models.deletion


def migrate_section_data_forward(apps, schema_editor):
    """Convert existing section CharField values to Section objects"""
    SchoolClass = apps.get_model('schools', 'SchoolClass')
    Section = apps.get_model('schools', 'Section')
    
    # Get all school classes with section values
    classes_with_sections = SchoolClass.objects.exclude(
        section__isnull=True
    ).exclude(section='')
    
    section_map = {}  # (school_id, section_name) -> section_id
    
    # First pass: create all Section objects
    for school_class in classes_with_sections:
        if not school_class.section or not school_class.section.strip():
            continue
            
        section_name = school_class.section.strip()
        key = (school_class.school_id, section_name)
        
        if key not in section_map:
            # Get or create Section
            section, created = Section.objects.get_or_create(
                school_id=school_class.school_id,
                name=section_name,
                defaults={'is_active': True}
            )
            section_map[key] = section.id
    
    # Second pass: update school classes with section_temp_id
    for school_class in classes_with_sections:
        if not school_class.section or not school_class.section.strip():
            continue
            
        section_name = school_class.section.strip()
        key = (school_class.school_id, section_name)
        
        if key in section_map:
            school_class.section_temp_id = section_map[key]
            school_class.save(update_fields=['section_temp_id'])


def migrate_section_data_reverse(apps, schema_editor):
    """Reverse: convert Section ForeignKey back to CharField"""
    # This is a no-op for reverse migration
    pass


def copy_temp_to_foreignkey(apps, schema_editor):
    """Copy section_temp_id values to section ForeignKey"""
    SchoolClass = apps.get_model('schools', 'SchoolClass')
    
    # Update all school classes that have a section_temp_id
    classes_to_update = SchoolClass.objects.exclude(section_temp_id__isnull=True)
    
    for school_class in classes_to_update:
        school_class.section_id = school_class.section_temp_id
        school_class.save(update_fields=['section_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        # Step 1: Create the Section model first
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la section')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.school', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        # Step 2: Add temporary integer field to store section IDs
        migrations.AddField(
            model_name='schoolclass',
            name='section_temp_id',
            field=models.IntegerField(null=True, blank=True),
        ),
        # Step 3: Migrate data: create Section objects from CharField values and populate temp field
        migrations.RunPython(migrate_section_data_forward, migrate_section_data_reverse),
        # Step 4: Remove old CharField
        migrations.RemoveField(
            model_name='schoolclass',
            name='section',
        ),
        # Step 5: Add new ForeignKey field
        migrations.AddField(
            model_name='schoolclass',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='schools.section', verbose_name='Section'),
        ),
        # Step 6: Copy temp_id to ForeignKey
        migrations.RunPython(copy_temp_to_foreignkey, migrations.RunPython.noop),
        # Step 7: Remove temp field
        migrations.RemoveField(
            model_name='schoolclass',
            name='section_temp_id',
        ),
        # Step 8: Update ordering
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['level', 'grade', 'section__name'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
    ]
