# Generated by Django 4.2.7 on 2026-01-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_schoolclass_options_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='period_max',
            field=models.PositiveSmallIntegerField(choices=[(10, '10'), (20, '20'), (40, '40'), (50, '50')], default=20, verbose_name='Maximum par période (points)'),
        ),
    ]
