# Generated by Django 4.2.7 on 2026-01-27 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_add_subject_period_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_max', models.PositiveSmallIntegerField(choices=[(10, '10'), (20, '20'), (40, '40'), (50, '50')], verbose_name='Note de base (max/période)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='schools.schoolclass', verbose_name='Classe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='schools.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Matière par classe',
                'verbose_name_plural': 'Matières par classe',
                'ordering': ['school_class', 'subject__name'],
                'unique_together': {('school_class', 'subject')},
            },
        ),
    ]
