# Generated by Django 4.2.7 on 2026-01-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0004_add_class_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='titulaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titular_classes', to='accounts.teacher', verbose_name='Enseignant titulaire'),
        ),
    ]
