# Generated by Django 4.2.7 on 2026-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_add_titulaire_to_schoolclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='period_max',
            field=models.PositiveSmallIntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90'), (100, '100')], verbose_name='Note de base (max/période)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='period_max',
            field=models.PositiveSmallIntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90'), (100, '100')], default=20, verbose_name='Maximum par période (points)'),
        ),
    ]
