# Generated by Django 4.2.7 on 2026-01-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_period_max_choices_10_to_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='next_class_name',
            field=models.CharField(blank=True, help_text="Ex. 4ème CG pour 3ème CG. Si ≥50% T.G., l'élève passe dans cette classe (année suivante).", max_length=100, null=True, verbose_name='Classe suivante (promotion)'),
        ),
    ]
