# Generated by Django 4.2.7 on 2026-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_add_next_class_name_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='is_terminal',
            field=models.BooleanField(default=False, help_text="Dernière année (ex. 6ème CG). Si ≥50% T.G., l'élève sort et rejoint les anciens élèves.", verbose_name='Année terminale'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='next_class_name',
            field=models.CharField(blank=True, help_text="Ex. 4ème CG pour 3ème CG. Si ≥50% T.G., l'élève y passe. Vide si année terminale.", max_length=100, null=True, verbose_name='Classe suivante (promotion)'),
        ),
    ]
