# Generated by Django 4.2.7 on 2026-01-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_former_student_graduation_year'),
        ('schools', '0008_add_is_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('promoted', 'Promu'), ('graduated', 'Diplômé / sorti'), ('withdrawn', 'Désinscrit')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='schools.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Inscription en classe',
                'verbose_name_plural': 'Inscriptions en classe',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'school_class')},
            },
        ),
    ]
