# Generated by Django 4.2.7 on 2026-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_add_teacher_to_classsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('promoted', 'Promu'), ('graduated', 'Diplômé / sorti'), ('withdrawn', 'Désinscrit'), ('echec', 'Échec')], default='active', max_length=20),
        ),
    ]
