# Generated by Django 4.2.7 on 2026-01-22 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Téléphone du destinataire')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échoué'), ('DELIVERED', 'Livré'), ('READ', 'Lu')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('provider', models.CharField(default='Twilio', max_length=50, verbose_name='Fournisseur')),
                ('provider_message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID message fournisseur')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livré le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='schools.school', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Log WhatsApp',
                'verbose_name_plural': 'Logs WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Téléphone du destinataire')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échoué'), ('DELIVERED', 'Livré')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('provider', models.CharField(default='Twilio', max_length=50, verbose_name='Fournisseur')),
                ('provider_message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID message fournisseur')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livré le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='schools.school', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Log SMS',
                'verbose_name_plural': 'Logs SMS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('meeting_date', models.DateTimeField(verbose_name='Date de la réunion')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='Durée (minutes)')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifiée'), ('CONFIRMED', 'Confirmée'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='SCHEDULED', max_length=20, verbose_name='Statut')),
                ('agenda', models.TextField(blank=True, null=True, verbose_name='Ordre du jour')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_parent_meetings', to='accounts.parent', verbose_name='Parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_meetings', to='schools.school', verbose_name='École')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_parent_meetings', to='accounts.student', verbose_name='Élève')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_parent_meetings', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Réunion parent-enseignant',
                'verbose_name_plural': 'Réunions parent-enseignant',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('GRADE', 'Note'), ('ATTENDANCE', 'Présence'), ('ASSIGNMENT', 'Devoir'), ('PAYMENT', 'Paiement'), ('ANNOUNCEMENT', 'Annonce'), ('MEETING', 'Réunion'), ('GENERAL', 'Général')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name="Type d'objet lié")),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name="ID de l'objet lié")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schools.school', verbose_name='École')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='schools.school', verbose_name='École')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('target_audience', models.CharField(choices=[('ALL', 'Tous'), ('STUDENTS', 'Élèves'), ('PARENTS', 'Parents'), ('TEACHERS', 'Enseignants'), ('ADMINS', 'Administrateurs')], default='ALL', max_length=20, verbose_name='Public cible')),
                ('send_sms', models.BooleanField(default=False, verbose_name='Envoyer par SMS')),
                ('send_whatsapp', models.BooleanField(default=False, verbose_name='Envoyer par WhatsApp')),
                ('send_notification', models.BooleanField(default=True, verbose_name='Envoyer notification')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='schools.school', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
            },
        ),
    ]
