# Generated by Django 4.2.7 on 2026-01-22 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('report_period_start', models.DateField(verbose_name='Début de période')),
                ('report_period_end', models.DateField(verbose_name='Fin de période')),
                ('academic_progress', models.TextField(verbose_name='Progrès académique')),
                ('behavior_observations', models.TextField(blank=True, null=True, verbose_name='Observations comportementales')),
                ('recommendations', models.TextField(verbose_name='Recommandations')),
                ('parent_feedback', models.TextField(blank=True, null=True, verbose_name='Retour du parent')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Brouillon')),
                ('is_shared_with_parent', models.BooleanField(default=False, verbose_name='Partagé avec le parent')),
                ('shared_at', models.DateTimeField(blank=True, null=True, verbose_name='Partagé le')),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='tutoring/reports/', verbose_name='Rapport PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_reports', to='schools.school', verbose_name='École')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_reports', to='accounts.student', verbose_name='Élève')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_reports', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': "Rapport d'encadrement",
                'verbose_name_plural': "Rapports d'encadrement",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutoringMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_type', models.CharField(choices=[('QUESTION', 'Question'), ('ADVICE', 'Conseil'), ('UPDATE', 'Mise à jour'), ('CONCERN', 'Préoccupation'), ('GENERAL', 'Général')], default='GENERAL', max_length=20, verbose_name='Type de message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('is_important', models.BooleanField(default=False, verbose_name='Important')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tutoring/attachments/', verbose_name='Pièce jointe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tutoring_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_messages', to='schools.school', verbose_name='École')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_tutoring_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_messages', to='accounts.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': "Message d'encadrement",
                'verbose_name_plural': "Messages d'encadrement",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedagogicalAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('advice', models.TextField(verbose_name='Conseil pédagogique')),
                ('category', models.CharField(choices=[('STUDY_HABITS', "Habitudes d'étude"), ('HOMEWORK', 'Devoirs'), ('BEHAVIOR', 'Comportement'), ('LEARNING', 'Apprentissage'), ('MOTIVATION', 'Motivation'), ('OTHER', 'Autre')], default='OTHER', max_length=50, verbose_name='Catégorie')),
                ('resources', models.TextField(blank=True, null=True, verbose_name='Ressources recommandées')),
                ('links', models.JSONField(blank=True, null=True, verbose_name='Liens utiles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogical_advices', to='schools.school', verbose_name='École')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogical_advices', to='accounts.student', verbose_name='Élève')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogical_advices', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Conseil pédagogique',
                'verbose_name_plural': 'Conseils pédagogiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
