# Generated by Django 4.2.7 on 2026-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Année de sortie'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_former_student',
            field=models.BooleanField(default=False, verbose_name='Ancien élève'),
        ),
    ]
