# Generated by Django 4.2.7 on 2026-02-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_former_student_graduation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur école'), ('TEACHER', 'Enseignant'), ('PARENT', 'Parent'), ('STUDENT', 'Élève'), ('ACCOUNTANT', 'Comptable'), ('DISCIPLINE_OFFICER', 'Chargé de discipline')], max_length=20, verbose_name='Rôle'),
        ),
    ]
