# Generated by Django 4.2.7 on 2026-01-22 11:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('POSITIVE', 'Comportement positif'), ('NEGATIVE', 'Comportement négatif')], max_length=10, verbose_name='Type')),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='Sévérité')),
                ('description', models.TextField(verbose_name='Description')),
                ('action_taken', models.TextField(blank=True, null=True, verbose_name='Action prise')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='schools.schoolclass', verbose_name='Classe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='accounts.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Fiche de discipline',
                'verbose_name_plural': 'Fiches de discipline',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('term', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2, verbose_name='Trimestre')),
                ('total_subjects', models.IntegerField(default=0, verbose_name='Nombre de matières')),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Moyenne générale')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rang')),
                ('total_students', models.IntegerField(blank=True, null=True, verbose_name='Total élèves')),
                ('teacher_comment', models.TextField(blank=True, null=True, verbose_name="Commentaire de l'enseignant")),
                ('principal_comment', models.TextField(blank=True, null=True, verbose_name='Commentaire du directeur')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='academics/report_cards/', verbose_name='Fichier PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='accounts.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-academic_year', '-term'],
                'unique_together': {('student', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('term', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2, verbose_name='Trimestre')),
                ('continuous_assessment', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Contrôle continu')),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name="Note d'examen")),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note totale')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.student', verbose_name='Élève')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_grades', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'subject', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('LATE', 'En retard'), ('EXCUSED', 'Excusé')], max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schools.schoolclass', verbose_name='Classe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.student', verbose_name='Élève')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='schools.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date'],
                'unique_together': {('student', 'date', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Année actuelle')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.school', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
                'unique_together': {('school', 'name')},
            },
        ),
    ]
