# Generated by Django 4.2.7 on 2026-01-27 11:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_add_subject_period_max'),
        ('accounts', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='application',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='conduite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Conduite'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='decision',
            field=models.CharField(blank=True, choices=[('PASSE', 'Passé'), ('DOUBLE', 'Double'), ('REPECHAGE', 'Avec repêchage')], max_length=20, null=True, verbose_name='Décision'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='reclamation_passed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Réussi au repêchage'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='reclamation_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.subject', verbose_name='Matière de repêchage'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne générale'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='term',
            field=models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3'), ('AN', 'Annuel (bulletin RDC)')], default='AN', max_length=2, verbose_name='Période'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='total_students',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'élèves"),
        ),
        migrations.CreateModel(
            name='GradeBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('s1_p1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='S1 - 1ère P. (Trav. journaliers)')),
                ('s1_p2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='S1 - 2ème P.')),
                ('s1_exam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='S1 - Examen')),
                ('total_s1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total S1')),
                ('s2_p3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='S2 - 3ème P.')),
                ('s2_p4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='S2 - 4ème P.')),
                ('s2_exam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='S2 - Examen')),
                ('total_s2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total S2')),
                ('total_general', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='T.G. (Total général)')),
                ('reclamation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Repêchage')),
                ('reclamation_passed', models.BooleanField(blank=True, null=True, verbose_name='Réussi au repêchage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_bulletins', to='accounts.student', verbose_name='Élève')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_bulletins', to='schools.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_grade_bulletins', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Note (bulletin RDC)',
                'verbose_name_plural': 'Notes (bulletin RDC)',
                'ordering': ['student', 'subject'],
                'unique_together': {('student', 'subject', 'academic_year')},
            },
        ),
    ]
