# Generated by Django 4.2.7 on 2026-01-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_backfill_student_class_enrollment'),
        ('academics', '0002_grade_bulletin_reportcard_rdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradebulletin',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_bulletins', to='schools.schoolclass', verbose_name='Classe (contexte de la note)'),
        ),
    ]
