# Generated by Django 4.2.7 on 2026-02-16 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0005_attendance_unique_school_class_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinerecord',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture'),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Fermé par'),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de résolution'),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution'),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par'),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ouvert'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='OPEN', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
