# Generated by Django 4.2.7 on 2026-02-16 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_former_student_graduation_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0006_add_discipline_status_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('APOLOGY', "Demande d'excuse"), ('PUNISHMENT_LIFT', 'Demande de levée de punition'), ('APPEAL', 'Recours'), ('DISCUSSION', 'Discussion')], max_length=20, verbose_name='Type de demande')),
                ('message', models.TextField(verbose_name='Message/Justification')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('response', models.TextField(blank=True, null=True, verbose_name="Réponse de l'école")),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipline_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='academics.disciplinerecord', verbose_name='Fiche de discipline')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_requests', to='accounts.parent', verbose_name='Parent')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_discipline_requests', to=settings.AUTH_USER_MODEL, verbose_name='Répondu par')),
            ],
            options={
                'verbose_name': 'Demande de discipline',
                'verbose_name_plural': 'Demandes de discipline',
                'ordering': ['-created_at'],
            },
        ),
    ]
