# Generated by Django 4.2.7 on 2026-01-22 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='CDF', max_length=3, verbose_name='Devise')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('MOBILE_MONEY_MPESA', 'M-Pesa'), ('MOBILE_MONEY_ORANGE', 'Orange Money'), ('MOBILE_MONEY_AIRTEL', 'Airtel Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CARD', 'Carte bancaire'), ('ONLINE', 'Paiement en ligne')], max_length=20, verbose_name='Méthode de paiement')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de référence')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de transaction')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='schools.school', verbose_name='École')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.student', verbose_name='Élève')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de reçu')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Fichier PDF')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Reçu de paiement',
                'verbose_name_plural': 'Reçus de paiement',
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='CDF', max_length=3, verbose_name='Devise')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='schools.school', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Type de frais',
                'verbose_name_plural': 'Types de frais',
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('term', models.CharField(blank=True, max_length=2, null=True, verbose_name='Trimestre')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.feetype', verbose_name='Type de frais')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='payments.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Paiement de frais',
                'verbose_name_plural': 'Paiements de frais',
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name="Numéro d'échéance")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Plan de paiement',
                'verbose_name_plural': 'Plans de paiement',
                'ordering': ['installment_number'],
                'unique_together': {('payment', 'installment_number')},
            },
        ),
    ]
