# Generated by Django 4.2.7 on 2026-02-16 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_add_meeting_groups_and_publication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SALARIES', 'Salaires'), ('MAINTENANCE', 'Entretien / Maintenance'), ('MATERIEL', 'Matériel pédagogique'), ('UTILITIES', 'Eau / Électricité / Internet'), ('EVENTS', 'Activités / Événements'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='CDF', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('PAID', 'Payée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('expense_date', models.DateField(blank=True, null=True, verbose_name='Date de la dépense')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='schools.school', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
