# Generated by Django 4.2.7 on 2026-02-16 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0012_add_meeting_groups_and_publication'),
        ('payments', '0002_add_school_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolexpense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('MOBILE_MONEY_MPESA', 'M-Pesa'), ('MOBILE_MONEY_ORANGE', 'Orange Money'), ('MOBILE_MONEY_AIRTEL', 'Airtel Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CARD', 'Carte bancaire'), ('ONLINE', 'Paiement en ligne')], default='CASH', max_length=30, verbose_name='Type de paiement'),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], max_length=5, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='CDF', max_length=3, verbose_name='Devise')),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True, verbose_name='Type de paiement')),
                ('source', models.CharField(choices=[('PAYMENT', 'Paiement parent'), ('EXPENSE', 'Dépense'), ('ADJUSTMENT', 'Ajustement'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Origine')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('reference_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Réf. type')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Réf. ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='schools.school', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-created_at'],
            },
        ),
    ]
