# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_expense_payment_method_and_cash_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolexpense',
            name='deduct_from_fee_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='expenses_deducted',
                to='payments.feetype',
                verbose_name='Imputé au type de frais',
            ),
        ),
    ]
