# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_schoolexpense_deduct_from_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolexpense',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='expenses/documents/', verbose_name='Document'),
        ),
    ]
