# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_schoolexpense_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='caisse/bons/', verbose_name="Bon d'entrée/sortie"),
        ),
    ]
