# Generated by Django 4.2.7 on 2026-01-22 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('meeting_type', models.CharField(choices=[('INDIVIDUAL', 'Individuelle'), ('GROUP', 'Groupe'), ('GENERAL', 'Générale')], default='INDIVIDUAL', max_length=20, verbose_name='Type')),
                ('meeting_date', models.DateTimeField(verbose_name='Date de la réunion')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='Durée (minutes)')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Lien visioconférence')),
                ('video_platform', models.CharField(blank=True, choices=[('ZOOM', 'Zoom'), ('TEAMS', 'Microsoft Teams'), ('GOOGLE_MEET', 'Google Meet'), ('OTHER', 'Autre')], max_length=50, null=True, verbose_name='Plateforme visio')),
                ('meeting_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de réunion')),
                ('meeting_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mot de passe')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifiée'), ('CONFIRMED', 'Confirmée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée'), ('RESCHEDULED', 'Reprogrammée')], default='SCHEDULED', max_length=20, verbose_name='Statut')),
                ('agenda', models.TextField(blank=True, null=True, verbose_name='Ordre du jour')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Rapport de réunion')),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='meetings/reports/', verbose_name='Rapport PDF')),
                ('parent_attended', models.BooleanField(default=False, verbose_name='Parent présent')),
                ('teacher_attended', models.BooleanField(default=False, verbose_name='Enseignant présent')),
                ('student_attended', models.BooleanField(default=False, verbose_name='Élève présent')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Rappel envoyé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to='accounts.parent', verbose_name='Parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='schools.school', verbose_name='École')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to='accounts.student', verbose_name='Élève')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Rôle')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('attended', models.BooleanField(default=False, verbose_name='Présent')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting', verbose_name='Réunion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to=settings.AUTH_USER_MODEL, verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Participant à la réunion',
                'verbose_name_plural': 'Participants aux réunions',
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
