# Generated by Django 4.2.7 on 2026-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_add_meeting_groups_and_publication'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='schools.schoolclass', verbose_name='Groupes/Classes'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Si publié, les participants peuvent voir la réunion', verbose_name='Publié'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publié le'),
        ),
    ]
