# Generated by Django 4.2.7 on 2026-02-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_add_meeting_groups_and_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individuelle'), ('GROUP', 'Groupe'), ('GENERAL', 'Générale'), ('TEACHER_MEETING', 'Réunion avec enseignant'), ('PARENT_MEETING', 'Réunion avec parent')], default='INDIVIDUAL', max_length=20, verbose_name='Type'),
        ),
    ]
