# Generated by Django 4.2.7 on 2026-01-22 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, verbose_name='Genre')),
                ('place_of_birth', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True, verbose_name='École précédente')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Nom du parent/tuteur')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='Téléphone du parent')),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du parent')),
                ('parent_profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession du parent')),
                ('parent_address', models.TextField(blank=True, null=True, verbose_name='Adresse du parent')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='enrollments/birth_certificates/', verbose_name='Acte de naissance')),
                ('previous_school_certificate', models.FileField(blank=True, null=True, upload_to='enrollments/certificates/', verbose_name="Certificat de l'école précédente")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enrollments/photos/', verbose_name='Photo')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='enrollments/medical/', verbose_name='Certificat médical')),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='enrollments/identity/', verbose_name="Pièce d'identité")),
                ('generated_student_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricule généré')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('COMPLETED', 'Complétée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_applications', to='schools.schoolclass', verbose_name='Classe demandée')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Révisé par')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schools.school', verbose_name='École')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par')),
            ],
            options={
                'verbose_name': "Demande d'inscription",
                'verbose_name_plural': "Demandes d'inscription",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complétée'), ('OVERDUE', 'En retard')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frais totaux')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('enrollment_date', models.DateField(verbose_name="Date d'inscription")),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reenrollments', to='schools.schoolclass', verbose_name='Classe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reenrollments', to='accounts.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Réinscription',
                'verbose_name_plural': 'Réinscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
