# Generated by Django 4.2.7 on 2026-01-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentapplication',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Postnom'),
        ),
    ]
